/* This file was generated by the generateJSLib.py file  at 16:25:26 on 28/06/2016 */
function _bsDivMod(newClass){ return withClass(_div(), newClass); }
function _bsContainer(){ return _bsDivMod('container'); }
function _bsApplyContainer(element){ return withAnotherClass(element, 'container'); }
function _bsContainerFluid(){ return _bsDivMod('container-fluid'); }
function _bsApplyContainerFluid(element){ return withAnotherClass(element, 'container-fluid'); }
function _bsRow(){ return _bsDivMod('row'); }
function _bsApplyRow(element){ return withAnotherClass(element, 'row'); }
function _bsPullRight(){ return _bsDivMod('pull-right'); }
function _bsApplyPullRight(element){ return withAnotherClass(element, 'pull-right'); }
function _bsPullLeft(){ return _bsDivMod('pull-left'); }
function _bsApplyPullLeft(element){ return withAnotherClass(element, 'pull-left'); }
function _bsCenterBlock(){ return _bsDivMod('center-block'); }
function _bsApplyCenterBlock(element){ return withAnotherClass(element, 'center-block'); }
function _bsPageFooter(){ return _bsDivMod('page-footer'); }
function _bsApplyPageFooter(element){ return withAnotherClass(element, 'page-footer'); }
function _bsTextCenter(){ return _bsDivMod('text-center'); }
function _bsApplyTextCenter(element){ return withAnotherClass(element, 'text-center'); }
function _bsJumbotron(){ return _bsDivMod('jumbotron'); }
function _bsApplyJumbotron(element){ return withAnotherClass(element, 'jumbotron'); }
function _bsColXs0(){ return _bsDivMod('col-xs-0'); }
function _bsApplyColXs0(element){ return withAnotherClass(element, 'col-xs-0'); }
function _bsColXs1(){ return _bsDivMod('col-xs-1'); }
function _bsApplyColXs1(element){ return withAnotherClass(element, 'col-xs-1'); }
function _bsColXs2(){ return _bsDivMod('col-xs-2'); }
function _bsApplyColXs2(element){ return withAnotherClass(element, 'col-xs-2'); }
function _bsColXs3(){ return _bsDivMod('col-xs-3'); }
function _bsApplyColXs3(element){ return withAnotherClass(element, 'col-xs-3'); }
function _bsColXs4(){ return _bsDivMod('col-xs-4'); }
function _bsApplyColXs4(element){ return withAnotherClass(element, 'col-xs-4'); }
function _bsColXs5(){ return _bsDivMod('col-xs-5'); }
function _bsApplyColXs5(element){ return withAnotherClass(element, 'col-xs-5'); }
function _bsColXs6(){ return _bsDivMod('col-xs-6'); }
function _bsApplyColXs6(element){ return withAnotherClass(element, 'col-xs-6'); }
function _bsColXs7(){ return _bsDivMod('col-xs-7'); }
function _bsApplyColXs7(element){ return withAnotherClass(element, 'col-xs-7'); }
function _bsColXs8(){ return _bsDivMod('col-xs-8'); }
function _bsApplyColXs8(element){ return withAnotherClass(element, 'col-xs-8'); }
function _bsColXs9(){ return _bsDivMod('col-xs-9'); }
function _bsApplyColXs9(element){ return withAnotherClass(element, 'col-xs-9'); }
function _bsColXs10(){ return _bsDivMod('col-xs-10'); }
function _bsApplyColXs10(element){ return withAnotherClass(element, 'col-xs-10'); }
function _bsColXs11(){ return _bsDivMod('col-xs-11'); }
function _bsApplyColXs11(element){ return withAnotherClass(element, 'col-xs-11'); }
function _bsColSm0(){ return _bsDivMod('col-sm-0'); }
function _bsApplyColSm0(element){ return withAnotherClass(element, 'col-sm-0'); }
function _bsColSm1(){ return _bsDivMod('col-sm-1'); }
function _bsApplyColSm1(element){ return withAnotherClass(element, 'col-sm-1'); }
function _bsColSm2(){ return _bsDivMod('col-sm-2'); }
function _bsApplyColSm2(element){ return withAnotherClass(element, 'col-sm-2'); }
function _bsColSm3(){ return _bsDivMod('col-sm-3'); }
function _bsApplyColSm3(element){ return withAnotherClass(element, 'col-sm-3'); }
function _bsColSm4(){ return _bsDivMod('col-sm-4'); }
function _bsApplyColSm4(element){ return withAnotherClass(element, 'col-sm-4'); }
function _bsColSm5(){ return _bsDivMod('col-sm-5'); }
function _bsApplyColSm5(element){ return withAnotherClass(element, 'col-sm-5'); }
function _bsColSm6(){ return _bsDivMod('col-sm-6'); }
function _bsApplyColSm6(element){ return withAnotherClass(element, 'col-sm-6'); }
function _bsColSm7(){ return _bsDivMod('col-sm-7'); }
function _bsApplyColSm7(element){ return withAnotherClass(element, 'col-sm-7'); }
function _bsColSm8(){ return _bsDivMod('col-sm-8'); }
function _bsApplyColSm8(element){ return withAnotherClass(element, 'col-sm-8'); }
function _bsColSm9(){ return _bsDivMod('col-sm-9'); }
function _bsApplyColSm9(element){ return withAnotherClass(element, 'col-sm-9'); }
function _bsColSm10(){ return _bsDivMod('col-sm-10'); }
function _bsApplyColSm10(element){ return withAnotherClass(element, 'col-sm-10'); }
function _bsColSm11(){ return _bsDivMod('col-sm-11'); }
function _bsApplyColSm11(element){ return withAnotherClass(element, 'col-sm-11'); }
function _bsColMd0(){ return _bsDivMod('col-md-0'); }
function _bsApplyColMd0(element){ return withAnotherClass(element, 'col-md-0'); }
function _bsColMd1(){ return _bsDivMod('col-md-1'); }
function _bsApplyColMd1(element){ return withAnotherClass(element, 'col-md-1'); }
function _bsColMd2(){ return _bsDivMod('col-md-2'); }
function _bsApplyColMd2(element){ return withAnotherClass(element, 'col-md-2'); }
function _bsColMd3(){ return _bsDivMod('col-md-3'); }
function _bsApplyColMd3(element){ return withAnotherClass(element, 'col-md-3'); }
function _bsColMd4(){ return _bsDivMod('col-md-4'); }
function _bsApplyColMd4(element){ return withAnotherClass(element, 'col-md-4'); }
function _bsColMd5(){ return _bsDivMod('col-md-5'); }
function _bsApplyColMd5(element){ return withAnotherClass(element, 'col-md-5'); }
function _bsColMd6(){ return _bsDivMod('col-md-6'); }
function _bsApplyColMd6(element){ return withAnotherClass(element, 'col-md-6'); }
function _bsColMd7(){ return _bsDivMod('col-md-7'); }
function _bsApplyColMd7(element){ return withAnotherClass(element, 'col-md-7'); }
function _bsColMd8(){ return _bsDivMod('col-md-8'); }
function _bsApplyColMd8(element){ return withAnotherClass(element, 'col-md-8'); }
function _bsColMd9(){ return _bsDivMod('col-md-9'); }
function _bsApplyColMd9(element){ return withAnotherClass(element, 'col-md-9'); }
function _bsColMd10(){ return _bsDivMod('col-md-10'); }
function _bsApplyColMd10(element){ return withAnotherClass(element, 'col-md-10'); }
function _bsColMd11(){ return _bsDivMod('col-md-11'); }
function _bsApplyColMd11(element){ return withAnotherClass(element, 'col-md-11'); }
function _bsColLg0(){ return _bsDivMod('col-lg-0'); }
function _bsApplyColLg0(element){ return withAnotherClass(element, 'col-lg-0'); }
function _bsColLg1(){ return _bsDivMod('col-lg-1'); }
function _bsApplyColLg1(element){ return withAnotherClass(element, 'col-lg-1'); }
function _bsColLg2(){ return _bsDivMod('col-lg-2'); }
function _bsApplyColLg2(element){ return withAnotherClass(element, 'col-lg-2'); }
function _bsColLg3(){ return _bsDivMod('col-lg-3'); }
function _bsApplyColLg3(element){ return withAnotherClass(element, 'col-lg-3'); }
function _bsColLg4(){ return _bsDivMod('col-lg-4'); }
function _bsApplyColLg4(element){ return withAnotherClass(element, 'col-lg-4'); }
function _bsColLg5(){ return _bsDivMod('col-lg-5'); }
function _bsApplyColLg5(element){ return withAnotherClass(element, 'col-lg-5'); }
function _bsColLg6(){ return _bsDivMod('col-lg-6'); }
function _bsApplyColLg6(element){ return withAnotherClass(element, 'col-lg-6'); }
function _bsColLg7(){ return _bsDivMod('col-lg-7'); }
function _bsApplyColLg7(element){ return withAnotherClass(element, 'col-lg-7'); }
function _bsColLg8(){ return _bsDivMod('col-lg-8'); }
function _bsApplyColLg8(element){ return withAnotherClass(element, 'col-lg-8'); }
function _bsColLg9(){ return _bsDivMod('col-lg-9'); }
function _bsApplyColLg9(element){ return withAnotherClass(element, 'col-lg-9'); }
function _bsColLg10(){ return _bsDivMod('col-lg-10'); }
function _bsApplyColLg10(element){ return withAnotherClass(element, 'col-lg-10'); }
function _bsColLg11(){ return _bsDivMod('col-lg-11'); }
function _bsApplyColLg11(element){ return withAnotherClass(element, 'col-lg-11'); }
